-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/wikimedia_editor_tasks_keys (
  wet_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  wet_key VARBINARY(255) NOT NULL,
  UNIQUE INDEX wet_key (wet_key),
  PRIMARY KEY(wet_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/wikimedia_editor_tasks_counts (
  wetc_user INT UNSIGNED NOT NULL,
  wetc_key_id INT UNSIGNED NOT NULL,
  wetc_lang VARBINARY(32) NOT NULL,
  wetc_count INT UNSIGNED DEFAULT 0 NOT NULL,
  wetc_revert_count INT UNSIGNED DEFAULT 0 NOT NULL,
  PRIMARY KEY(
    wetc_user, wetc_key_id, wetc_lang
  )
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/wikimedia_editor_tasks_edit_streak (
  wetes_user INT UNSIGNED NOT NULL,
  wetes_streak_length INT UNSIGNED NOT NULL,
  wetes_last_edit_time BINARY(14) DEFAULT '19700101000000' NOT NULL,
  PRIMARY KEY(wetes_user)
) /*$wgDBTableOptions*/;
